/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import javax.swing.JFileChooser;

/**
 *
 * @author Rebeca
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btcargararch = new javax.swing.JButton();
        btagregarusu = new javax.swing.JButton();
        btagrefarconex = new javax.swing.JButton();
        bteliminarusu = new javax.swing.JButton();
        bteliminarconex = new javax.swing.JButton();
        btmostrargraf = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(173, 194, 216));

        btcargararch.setText("Cargar Archivo");
        btcargararch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcargararchActionPerformed(evt);
            }
        });

        btagregarusu.setText("Agrgar Usuario");

        btagrefarconex.setText("Agregar Conexión");

        bteliminarusu.setText("Eliminar Usuario");

        bteliminarconex.setText("Eliminar Conexión");

        btmostrargraf.setText("Mostrar Grafo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btcargararch, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btagregarusu, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btagrefarconex, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bteliminarusu, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bteliminarconex, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btmostrargraf, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(btcargararch)
                .addGap(87, 87, 87)
                .addComponent(btagregarusu)
                .addGap(87, 87, 87)
                .addComponent(btagrefarconex)
                .addGap(87, 87, 87)
                .addComponent(bteliminarusu)
                .addGap(87, 87, 87)
                .addComponent(bteliminarconex)
                .addGap(76, 76, 76)
                .addComponent(btmostrargraf)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 912, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btcargararchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcargararchActionPerformed

        
        
        
        fcSelectorArchivo = new JFileChooser();
        objListaString = new ListaDin<>();
        conjUsuarios = new ListaDin<>();
        conjRelaciones = new ListaDin<>();
        File archivoALeer;
        File openedFile;
        //solucion

        String lineaTxt;
        
        Boolean selectorDeConj = false;        
        String stConjunto = "";
        Scanner scTxtIn;
        //operacion con filechooser
        
        int checkInput = fcSelectorArchivo.showOpenDialog(null);

        if (checkInput == JFileChooser.APPROVE_OPTION) {
            openedFile = fcSelectorArchivo.getSelectedFile();
            //solo para pruebas
            System.out.println("File Name: " + openedFile.getName());
            System.out.println("File Location: " + openedFile.getAbsolutePath());

            try {//Scanee puede lanzar excepciones IO

                scTxtIn = new Scanner(openedFile);
                //Limpiar area de texto
                tAreaMostrarTexto.setText("");
                //Leer linea por linea el contenido para en textArea y para crear los conjuntos
                while (scTxtIn.hasNextLine()) {
                    lineaTxt = scTxtIn.nextLine();
                    // llenar textArea con la informacion del archivo de texto
                    tAreaMostrarTexto.append(lineaTxt + "\n");
                    //construccion de conjuntos
                    //
                    if (  '@' !=  lineaTxt.charAt(0)  ) {
                        stConjunto = lineaTxt.toUpperCase();
                        //solo para pruebas
                        System.out.println("Linea 154: " + stConjunto);
                    } else {
                        switch (stConjunto) {
                            case "USUARIOS":
                                Vertex v = new Vertex(lineaTxt, 0, 0);
                                conjUsuarios.agregarFinal(v);
                                break;
                            case "RELACIONES":
                                //Usando el separador "," devuelve un array con los dos usuarios incluyecto el espacio en blanco, si lo hubiese
                                String[] parUsuarios = lineaTxt.split(",");
                                //@a, @b
                                //parUsuarios[@a][@b]
                                //             0   1
                                //ListaDin<String[]> 
                                //creamos el objeto Edge, creando los 
                                break;

                        }

                    }

                }
                //solo para pruebas
                conjUsuarios.imprimirLista();

            } catch (FileNotFoundException ex) {
                ex.printStackTrace();
            }
        }



    }//GEN-LAST:event_btcargararchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btagrefarconex;
    private javax.swing.JButton btagregarusu;
    private javax.swing.JButton btcargararch;
    private javax.swing.JButton bteliminarconex;
    private javax.swing.JButton bteliminarusu;
    private javax.swing.JButton btmostrargraf;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
