/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileSystemView;
import org.graphstream.graph.Graph;
import org.graphstream.graph.implementations.MultiGraph;
import org.graphstream.graph.implementations.SingleGraph;
import proyecto1edd.Lista;
import proyecto1edd.Grafo;

/**
 *
 * @author Alessandra
 */
public class Interfaz extends javax.swing.JFrame {
    
    public Grafo grafo;// = new Grafo();
    public Graph graph;
    public String rutaAbsolutadeArchivo;

    public Interfaz() {
        grafo = new Grafo();
        graph = new SingleGraph("embedded");
        initComponents();
    }

    public void mostrarGrafo() {
        System.setProperty("org.graphstream.ui", "swing");
        graph.display();

    }

    public void leerArchivo() {
        Grafo.contRelaciones = 0;
        Grafo.contUsuarios = 0;
        grafo.arrUsuarios =  new String[Grafo.MAX_USUARIOS];
        String stConjunto = null;
        JFileChooser fChooser;
        File Archabierto = null;
        Scanner in = null;
        try {
            fChooser = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());

            int returnValue = fChooser.showOpenDialog(null);


            if (returnValue == JFileChooser.APPROVE_OPTION) {
                Archabierto = fChooser.getSelectedFile();
                rutaAbsolutadeArchivo = Archabierto.getAbsolutePath();
            }

            in = new Scanner(Archabierto);

            while (in.hasNextLine()) {
                String linea;
                while (in.hasNextLine()) {
                    linea = in.nextLine();
                    if ('@' != linea.charAt(0)) {
                        stConjunto = linea.toUpperCase();
                    } else {
                        switch (stConjunto) {
                            case "USUARIOS":
                                grafo.agregarUsuario(linea);
                                graph.addNode(linea);
                                //Grafo.contUsuarios++;
                                break;
                            case "RELACIONES":
                                String[] rel1Rel2 = linea.split(",");
                                rel1Rel2[0] = rel1Rel2[0].strip();
                                rel1Rel2[1] = rel1Rel2[1].strip();
                                grafo.agregarRelacion(rel1Rel2);
                                graph.addEdge(rel1Rel2[0] + rel1Rel2[1], rel1Rel2[0], rel1Rel2[1]);
                                //Grafo.contRelaciones++;

                        }
                    }
                }
            }
            in.close();

        } catch (FileNotFoundException e) {
            System.out.println("Un error ha ocurrido.");
            e.printStackTrace();
        } finally {
            in.close();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btcargararch = new javax.swing.JButton();
        btagregarusu = new javax.swing.JButton();
        btagrefarconex = new javax.swing.JButton();
        bteliminarusu = new javax.swing.JButton();
        bteliminarconex = new javax.swing.JButton();
        btmostrargraf = new javax.swing.JButton();
        mostrarmatady = new javax.swing.JButton();
        mostrarusu = new javax.swing.JButton();
        mostrarconex = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taNotePad = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(173, 194, 216));

        btcargararch.setText("Cargar Archivo");
        btcargararch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcargararchActionPerformed(evt);
            }
        });

        btagregarusu.setText("Agrgar Usuario");
        btagregarusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btagregarusuActionPerformed(evt);
            }
        });

        btagrefarconex.setText("Agregar Conexión");
        btagrefarconex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btagrefarconexActionPerformed(evt);
            }
        });

        bteliminarusu.setText("Eliminar Usuario");

        bteliminarconex.setText("Eliminar Conexión");

        btmostrargraf.setText("Mostrar Grafo");
        btmostrargraf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmostrargrafActionPerformed(evt);
            }
        });

        mostrarmatady.setText("Mostrar matriz de Adyacencia");
        mostrarmatady.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarmatadyActionPerformed(evt);
            }
        });

        mostrarusu.setText("Mostrar Usuarios");
        mostrarusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarusuActionPerformed(evt);
            }
        });

        mostrarconex.setText("Mostrar conexiones");
        mostrarconex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarconexActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btcargararch, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btagregarusu, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btagrefarconex, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bteliminarusu, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bteliminarconex, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btmostrargraf, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostrarmatady, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostrarusu, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostrarconex, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btcargararch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mostrarusu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mostrarconex)
                .addGap(142, 142, 142)
                .addComponent(btmostrargraf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mostrarmatady)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addComponent(btagregarusu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bteliminarusu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btagrefarconex)
                .addGap(18, 18, 18)
                .addComponent(bteliminarconex)
                .addGap(80, 80, 80))
        );

        taNotePad.setColumns(20);
        taNotePad.setRows(5);
        jScrollPane1.setViewportView(taNotePad);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btcargararchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcargararchActionPerformed

        leerArchivo();       
    }//GEN-LAST:event_btcargararchActionPerformed

    private void mostrarmatadyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarmatadyActionPerformed
        grafo.imprimirMatriz(taNotePad);
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarmatadyActionPerformed

    private void mostrarusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarusuActionPerformed
        taNotePad.setText("");
        grafo.imprimirUsuarios(taNotePad);
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarusuActionPerformed

    private void mostrarconexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarconexActionPerformed
      taNotePad.setText("");
        grafo.imprimirRelaciones(taNotePad);
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarconexActionPerformed

    private void btagregarusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btagregarusuActionPerformed
        String nombreUsuario;
        nombreUsuario = JOptionPane.showInputDialog("Ingrese nombre de usuario");
        taNotePad.append("@"+nombreUsuario);        // TODO add your handling code here:
    }//GEN-LAST:event_btagregarusuActionPerformed

    private void btmostrargrafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmostrargrafActionPerformed
       System.setProperty("org.graphstream.ui", "swing");
       graph.display();        
// TODO add your handling code here:
    }//GEN-LAST:event_btmostrargrafActionPerformed

    private void btagrefarconexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btagrefarconexActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_btagrefarconexActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btagrefarconex;
    private javax.swing.JButton btagregarusu;
    private javax.swing.JButton btcargararch;
    private javax.swing.JButton bteliminarconex;
    private javax.swing.JButton bteliminarusu;
    private javax.swing.JButton btmostrargraf;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mostrarconex;
    private javax.swing.JButton mostrarmatady;
    private javax.swing.JButton mostrarusu;
    private javax.swing.JTextArea taNotePad;
    // End of variables declaration//GEN-END:variables
}
